# Generated by Django 4.1 on 2022-08-30 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coberturasalud',
            old_name='fecha_afiliacion',
            new_name='fecha_creacion',
        ),
    ]
