# Generated by Django 4.1 on 2022-09-12 14:56

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0003_autos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=255, verbose_name='Nombres de Autor')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Apellidos de Autor')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='twitter')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='instagram')),
                ('correo', models.URLField(blank=True, null=True, verbose_name='correo electronico')),
                ('estado', models.BooleanField(default=True, verbose_name='Autor Activo/No Activo')),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tema', models.CharField(max_length=100, verbose_name='Nombre del Tema')),
                ('estado', models.BooleanField(default=True, verbose_name='Tema Activad/Tema no activado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
        migrations.AlterField(
            model_name='autos',
            name='escuderias',
            field=models.CharField(choices=[('Ferrari', 'Ferrari'), ('Mercedes', 'Mercedes'), ('Alpine', 'Alpine'), ('Haas', 'Haas'), ('Alfa Romeo', 'Alfa Romeo'), ('Aston Martin', 'Aston Martin'), ('Alphatauri', 'Alphatauri'), ('Williams', 'Williams'), ('Red Bull', 'Red Bull'), ('Mclaren', 'Mclaren')], default='Ferrari', max_length=30),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=90, verbose_name='Titulo')),
                ('slug', models.CharField(max_length=100, verbose_name='Slug')),
                ('contenido', ckeditor.fields.RichTextField()),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripcion')),
                ('imagen', models.URLField(max_length=255)),
                ('estado', models.BooleanField(default=True, verbose_name='Publicado/No publicado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='fecha de creacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMVT.autor')),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppMVT.tema')),
            ],
        ),
    ]
