# Generated by Django 4.1 on 2022-09-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0004_autor_tema_alter_autos_escuderias_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tema',
            old_name='fecha_creacion',
            new_name='creado',
        ),
    ]
