# Generated by Django 4.1 on 2022-09-19 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0005_rename_fecha_creacion_tema_creado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tema',
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tema',
        ),
    ]
