# Generated by Django 4.1 on 2022-09-28 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppMVT', '0008_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Post'},
        ),
    ]
